modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="createmilitary_support"
version="1.0.0"
displayName="create:military_support"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="s204157, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.createmilitary_support]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.createmilitary_support]]
    modId="additions"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createmilitary_support]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration